### ISSUE TITLE
"calling set on destroyed object" because of not cancelled timer

### ISSUE THREAD

**Issue by frank06** [marzubov/ember-calendar#31]
In https://github.com/marzubov/ember-calendar/blob/develop/addon/components/as-calendar/timetable.js#L109 the timer is not being properly cancelled (via `Ember.run.cancel`)

This causes buggy behavior like I am seeing with Ember throwing an error because it couldn't set a property on a destroyed object: `"calling set on destroyed object"`

**Comment by marzubov** [comment]
Hi @frank06 
Thank You for finding out what caused those errors. I didn't have much time to investigate this.
By the way, PRs are welcomed 👍
