### ISSUE TITLE
Events bleeding over in month view

### ISSUE THREAD

**Issue by jamesdixon** [marzubov/ember-calendar#4]
If I set an event in day/week view that is multiple hours long, I'm seeing it bleed over into the day just below in the month view.

![image](https://cloud.githubusercontent.com/assets/110114/18028482/f339bb8a-6c3d-11e6-8445-88f6dc62b130.png)

I reproduced this on the demo site.

**Comment by jamesdixon** [comment]
@marzubov given that this is the month view, I believe all events should be a fixed height. In the case that there are more events that can fit in a cell, there should be an indicator of how many more events are scheduled for that day.

Example from iCal:

![image](https://cloud.githubusercontent.com/assets/110114/18029149/7ea0506c-6c4d-11e6-85bd-6da5b5893e69.png)

**Comment by marzubov** [comment]
@jamesdixon I've already done this somewhere.
Will look into this tomorrow.

**Comment by jamesdixon** [comment]
@marzubov were you able to find your fix for this?

**Comment by marzubov** [comment]
@jamesdixon Updated [demo page](https://marzubov.github.io/ember-calendar/demo/). Please take a look.

**Comment by jamesdixon** [comment]
@marzubov looks great!
